# frozen_string_literal: true

source 'https://rubygems.org'

gem 'cukewrapper', path: '..'

group :cukewrapper_plugins do
  gem 'cukewrapper_data', path: '../../cukewrapper_data'
  gem 'cukewrapper_inline_jsonpath', path: '../../cukewrapper_inline_jsonpath'
  gem 'cukewrapper_mocktarget', path: '../../cukewrapper_mocktarget'
end
